name: Commit date
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
      - name: write date
        run: date > ./current_time.txt
      - name: configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout $GITHUB_REF
          git add .
          git commit -m "Updating date"
          git push -u origin master
